version: '3.9'

services:
  mongo:
    image: bitnami/mongodb:latest
    restart: unless-stopped
    environment:
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=12345678
      - MONGODB_USERNAME=hydro
      - MONGODB_PASSWORD=12345678
      - MONGODB_DATABASE=hydro
    volumes:
      - ./mongodb-data:/bitnami/mongodb
  oj-backend:
    image: hsoj-hydro:latest
    container_name: oj-backend
    ports:
      - 8888:8888
    depends_on:
      - mongo
    environment:
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_USER=hydro
      - DB_PASSWD=12345678
    volumes:
      - ./hydro:/root/.hydro
      - ./testdata:/data/file
  oj-judge:
    image: hsoj-hydro:latest
    container_name: oj-judge
    restart: always
    privileged: true
    depends_on:
      - oj-backend
    volumes:
      - ./data/judge:/root/.config/hydro