name: CI

on:
  repository_dispatch: 
    types: [npm_build]
  workflow_dispatch:

env:
  CI: true
  YARN_ENABLE_IMMUTABLE_INSTALLS: 'false'
  BUILD_UI: 'true'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 2
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v3
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            yarn.lock
            .cache
            **/tsconfig.tsbuildinfo
          key: cache-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            cache-${{ github.ref }}-
            cache-
      - name: Clear Cache
        if: "contains(github.event.head_commit.message, 'skip-cache')"
        run: |
          rm -rf node_modules yarn.lock **/tsconfig.tsbuildinfo
      - name: Config And Install
        run: |
          cat << EOF >> .yarnrc.yml
          npmRegistryServer: "https://registry.npmjs.org"
          npmPublishRegistry: "https://${{ secrets.NPM_REGISTRY }}"
          npmRegistries:
            "//${{ secrets.NPM_REGISTRY }}":
              npmAuthIdent: "${{ secrets.NPM_USERNAME }}:${{ secrets.NPM_PASSWORD }}"
          EOF
          git config --global user.name TsukiyukiMiyako
          git config --global user.email admin@acm.tohsakura.com
          yarn
          yarn dedupe
        env:
          LICENSE_KEY: ${{ secrets.MAXMIND_KEY }}
      - name: Get specific changed files
        id: ui-changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            /package.json
            .eslint*
            packages/ui-default/**
            packages/utils/**
            .github/workflows/**
      - name: Build
        run: |
          node -r @hydrooj/register build/tagger.ts
          yarn build:ui:iconfont
          parallel --tty -j+0 yarn ::: build build:ui:production:webpack
      - name: Publish
        run: yarn workspaces foreach -A npm publish --access public --tag latest